import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="nav">
          <Link href={"/"}>Home</Link>
          <Link href={"/articles"}>Articles</Link>
          <Link href={"/articles/kjdksadaklsjd"}>not existed Articles</Link>

          <div>
            <Link href={"/section"}>Section</Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
